#!/bin/sh

# run it as root

set -eux

readonly DOMAIN="${1}"
readonly PASSWORD="${2}"

readonly CONFIG_FILE='adtool.cfg'

emerge --oneshot --ask n --noreplace net-nds/adtool

sed "s|DOMAIN|${DOMAIN}|; s|PASSWORD|${PASSWORD}|" \
	< "${CONFIG_FILE}" > "/etc/$(basename "${CONFIG_FILE}")"
